#+TITLE: Red Wine Quality Classifier
#+AUTHOR: João Lucas Correia Barbosa de Farias
#+AUTHOR: Júlio Freire
#+EMAIL: joao.farias.080@ufrn.edu.br

* Deployment of a full decision tree pipeline
This project consists of classifying red wine quality based on several chemical proprieties of the wine. A full pipeline was created to handle processing of the features and the training of the model, which was performed using Decision Tree. Then, the model and target encoder were exported to [[https://wandb.ai/site][Weights & Biases]] where there were later retrieved for the deployment of the model. The deployment was possible due to [[https://github.com/][GitHub]] CI/CD integration with [[https://www.heroku.com/][Heroku]]. The final product is available for testing at [[https://red-wine-quality-ml.herokuapp.com/][Red Wine Quality App]] where anyone can input the values for the wine features and get back a result for its quality: either 'good' or 'bad'.

* About the Authors
The authors of this project are [[https://github.com/jotafarias13][João Lucas Farias]] and [[https://github.com/juliofreire][Júlio Freire]]. The project was created as part of a Graduate Level course on Machine Learning at the Graduate Program in Electrical and Computer Engineering at the Federal University of Rio Grande do Norte (UFRN), Brasil. The course is taught by [[https://github.com/ivanovitchm][Professor Ivanovitch Silva]]. The goal of the project was to teach the students how to create a Pipeline for Machine Learning algorithms (along with many good practices in ML programming), train the model and deploy the exported model for production. This way, anyone can test and verify the performance of the model. By using [[https://wandb.ai/site][Weights & Biases]], [[https://github.com/][GitHub]] and [[https://www.heroku.com/][Heroku]], we were able to train the model and deploy it.




