#+TITLE: Model Card -- Red Wine Quality
#+AUTHOR: João Lucas Correia Barbosa de Farias
#+AUTHOR: Júlio Freire
#+EMAIL: joao.farias.080@ufrn.edu.br

* Model Details
- João Lucas Farias and Júlio Freire are the authors of this model.
- The dataset was taken from Kaggle and are related to red and white variants of the Portuguese "Vinho Verde" wine.
- A full pipeline was developed using Google Colab and Weights & Biases.
- A Decision Tree was used to train the model.

* Intended Use
- This model is intended to serve as an educational tool, to help students understand the basics of Machine Learning algorithm implementation and good practices. By creating a full pipeline and splitting all relevant steps in individual files, the code created to train the model serves as example for future students.

* Factors
- All data used to train, validate and test the model are related to red and white variants of the Portuguese "Vinho Verde" wine. Hence, they belong to a single group (or family) of wines with somewhat similar characteristics.

* Metrics
- Evaluation metrics used in this project include Accuracy, Precision, Recall and F1.


  | Run                        | Accuracy | Precision | Recall |     F1 |
  | Train [[https://wandb.ai/ppgeec-ml-jj/red_wine_quality/runs/1rox5a1o/overview][jumping-resonance-63]] |   0.8636 |    0.5000 | 0.4615 | 0.4800 |
  | Test [[https://wandb.ai/ppgeec-ml-jj/red_wine_quality/runs/33eooynf/overview][zany-cosmos-25]]        |   0.8382 |    0.3830 | 0.3273 | 0.3529 |

* Evaluation Data
- The dataset used in this project are related to red and white variants of the Portuguese "Vinho Verde" wine.
- It has several features with physiochemical properties of the wines such as pH, sulphates, chlorides, density, alcohol etc.
- The target feature is the quality of the wine which is an integer number ranging from 3 to 8.
- After the EDA we noticed the target feature could be transformed into 'good' or 'bad' to decrease the imbalance of the set.
- The dataset can be downloaded from [[https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009][Kaggle]].
- Only 30% of the whole dataset was segregated for testing purposes. The other 70% was used for training.
- The test set can be found in our Weights & Biases project [[https://wandb.ai/ppgeec-ml-jj/red_wine_quality/artifacts/segregated_data/test.csv/][artifact]].

* Training Data
- In the train step, another segregation was done. This time, 70% of the train set was used for training and the other 30% for validating the trained model, that is, for hyperparameter tuning.
- The train set can be found in our Weights & Biases project [[https://wandb.ai/ppgeec-ml-jj/red_wine_quality/artifacts/segregated_data/train.csv/][artifact]].

* Quantitative Analysis
- The confusion matrix for the best model against the validation set can be seen [[file:~/Sync/Jota/Academico/Pós-Graduação/UFRN/Doutorado/2022-1/Aprendizagem de Máquina/wine-quality-ml/images/confusion_matrix_best_model.pdf][here]].
- The feature importante plot for the best model trained can be seen [[file:~/Sync/Jota/Academico/Pós-Graduação/UFRN/Doutorado/2022-1/Aprendizagem de Máquina/wine-quality-ml/images/feature_importance_best_model.pdf][here]].
- The confusion matrix for the best model simulated with the test set can be seen [[file:~/Sync/Jota/Academico/Pós-Graduação/UFRN/Doutorado/2022-1/Aprendizagem de Máquina/wine-quality-ml/images/confusion_matrix_test.pdf][here]].

* Ethical Considerations
- The quality of a wine, although related to its physiochemical properties, are not defined only by them. Also, this trained model should not be regarded as an app to determine the quality of every wine since it only encapsules the characteristics of the red and white variants of the Portugues "Vinho Verde" wine.

* Caveats and Recommendations
- The dataset was used to create a Decision Tree Classifier model with the sole intention of being used as an educational tool.
- The dataset does not capture wines from others parts of the world with different climates (which can dramatically the characteristics of the wine).
- Important issues related to dataset imbalance exist and should be properly treated with adequate techniques.

